# Generated by Django 3.2.5 on 2021-07-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_keyword_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='description',
            field=models.TextField(),
        ),
    ]
