# Generated by Django 3.2.5 on 2021-07-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_keyword_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='description',
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(choices=[('amorphous', 'amorphous'), ('thermoset', 'thermoset'), ('elastomer', 'elastomer')], max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='keywords',
            field=models.ManyToManyField(to='api.Keyword'),
        ),
    ]
