# Generated by Django 3.2.5 on 2021-07-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210729_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='keywords',
        ),
        migrations.AddField(
            model_name='material',
            name='keywords',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
